# Generated by Django 5.2.7 on 2025-10-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
