# Generated by Django 5.2.7 on 2025-10-31 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_usermodel_email_verified_alter_usermodel_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfirmationTokenModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.usermodel",
                    ),
                ),
            ],
        ),
    ]
