# Generated by Django 5.2.7 on 2025-11-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailConfirmationTokenModel",
        ),
    ]
