# Generated by Django 5.2.7 on 2025-11-05 18:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_usermodel_email_verified_alter_usermodel_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeTemplateModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResumeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resume_name", models.CharField(max_length=64)),
                ("job_title", models.CharField(blank=True, max_length=64)),
                ("first_name", models.CharField(blank=True, max_length=64)),
                ("last_name", models.CharField(blank=True, max_length=64)),
                ("email", models.EmailField(blank=True, max_length=64)),
                ("phone", models.CharField(blank=True, max_length=25)),
                ("country", models.CharField(blank=True, max_length=64)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="users.usermodel",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        db_column="template_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resumes",
                        to="resume.resumetemplatemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128)),
                ("link", models.URLField(blank=True, max_length=1000)),
                ("link_to_repo", models.URLField(blank=True, max_length=1000)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("sort_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        db_column="resume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="resume.resumemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128)),
                ("link", models.URLField(blank=True, max_length=1000)),
                ("sort_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        db_column="resume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="resume.resumemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LanguageModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=128)),
                ("level", models.CharField(blank=True, max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        db_column="resume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="resume.resumemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("school", models.CharField(blank=True, max_length=128)),
                ("degree", models.CharField(blank=True, max_length=128)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("start_end_date", models.CharField(blank=True, max_length=128)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("sort_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        db_column="resume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="resume.resumemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course", models.CharField(blank=True, max_length=128)),
                ("institution", models.CharField(blank=True, max_length=128)),
                ("start_end_date", models.CharField(blank=True, max_length=128)),
                ("sort_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        db_column="resume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="resume.resumemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128)),
                (
                    "level",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("sort_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        db_column="resume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="resume.resumemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperienceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=128)),
                ("employer", models.CharField(blank=True, max_length=128)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("start_end_date", models.CharField(blank=True, max_length=128)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("sort_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        db_column="resume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experience",
                        to="resume.resumemodel",
                    ),
                ),
            ],
        ),
    ]
