# Generated by Django 5.2.7 on 2025-11-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resumetemplatemodel",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
